name: "OPA Policy and Config Check"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "project directory of the stack for policy to run"
        required: true
        default: "cdp_creslab"

jobs:
  opa-security-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: Setup Node Version
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          npm ci -D
      # - name: Synth CDK stack for ${{ github.event.inputs.tag }}
      #   run: |
      #     cd ${{ github.workspace }}/${{ github.event.inputs.tag }}
      #     pwd
      #     npx cdk --require-approval never --resolveJsonModule --toolkit-stack-name=CdpCdkToolkit --context environ=staging synth -o opa.out
      - name: "Install OPA binary and JQ"
        run: |
          cd /tmp
          curl -L -o opa https://github.com/open-policy-agent/opa/releases/download/v0.11.0/opa_linux_amd64
          chmod +x opa
          sudo apt install -y jq
      - name: "Run Security Policy Check"
        # if: ${{ contains(github.event.head_commit.message, github.event.inputs.tag) }}
        run: |
          cd ${{ github.workspace }}/cdp_opa_security_policies
          /tmp/opa eval --format json -i ${{ github.workspace }}/opa.out/*Creslab/*.template.json -d s3 "data"
